### PR TITLE
Update Portuguese (pt_PT) translation

### PR DESCRIPTION
**Pull request by hugok79**
Minor corrections

### CODE REVIEW

**Comment by ib** [comment]
I have a few older commits that I need to check and release first. Your translation will follow immediately afterwards.

**Comment by ib** [comment]
By the way, if you want a period at the end of a sentence, feel free to do so, even if there is none in the original English text. Only you can decide how the translation looks best.

**Comment by hugok79** [comment]
Yes I know. But normally, I always leave it according to the original string even though sometimes it is the original .pot file that is wrong. Sometimes there are also a space at the end of the original string that shouldn't even be there...
Poedit always warn us about those kind of "errors".
I always try to leave the translation according to the original and in a way that sounds better for Portuguese users. The ideal is to make the translation consistent and as perfect as possible but as I also translate a lot of stuff and sometimes, only by thoroughly using the software itself to see if the translation is well done and typo-free!

**Comment by hugok79** [comment]
By the way, wouldn't it be better to create a .pot file in the /po directory and update it so that the translators could update their translation from that .pot file? Then each translator could create a Pull Request to update their respective translation?
Or use a translation platform like Transifex or Weblate...

**Comment by ib** [comment]
The problem is that most of the time there is no code in the repository for the translations yet. With translations from the .pot file (waiting for the code), many translations would probably not even be ready at the time of release. Collecting translations early allows me to release when I want and directly after finishing my release to-do list.
I don't have time to familiarize with a translation platform and there are only a few new texts per release (like two this time).

**Comment by hugok79** [comment]
Yes I understand.

**Comment by ib** [comment]
Applied.

**Pull request closed without merging**
