### PR TITLE
Add support for GTK+ 3

### PR DESCRIPTION
**Pull request by City-busz**
Provide full support for GTK+ 3 by fixing all deprecations in Xarchiver. It keeps the compatibility with GTK+ 2 by using the --disable-gtk3 configure flag.

### CODE REVIEW

**Comment by ib** [comment]
I'll have to test this which may take a while.

**Comment by ib** [comment]
Your patch compiles with GTK+ 3, but there are a few issues.

Not all of your changes still compile with glib/gtk+ >= 2.10.0, so the requirements have to be adjusted.

Since I'm developing with GTK+ 2, I'd like this to be the default (but GTK+ 3 taking precedence over GTK+ 2 if both are present).

There are warnings other than deprecated ones to be fixed for both GTK+ 2 and GTK+ 3.

So would you mind me splitting up your patch (applying it slightly changed but still with your authorship)?

**Comment by City-busz** [comment]
Yes, it's fine for me. My patch is targeted for GTK+ 2.24 and probably it fails with older versions.

**Comment by ib** [comment]
Everything applied, thanks.

Compiles and runs for me for both GTK+ 2 and 3, but please check and report back. I'll make a new release then.

**Comment by City-busz** [comment]
Thanks, it works fine for me too. It was more difficult to keep the compatibility with older GTK+ 2 releases, but you did a good job.

**Comment by ib** [comment]
Version 0.5.4.7 with GTK+ 3 support has been released.

**Pull request closed without merging**
